### PR TITLE
fixes showing siblings in archive-browser, closes #312

### LINKED ISSUE #312: Archive: browser, only shows parent doc
/documents/smga-documents-110000045

Navigating to an archive document, I only see the parent item.

screen shot 2016-08-17 at 12 51 49

### PR DESCRIPTION
**Pull request by Danwhy**
ref #312

### CODE REVIEW

File: lib/get-archive-and-children.js [hunk 1]
```diff
@@ -35,6 +35,7 @@ module.exports = (elastic, config, request, callback) => {
 
     getChildArchives(elastic, parentID, function (err, siblings) {
     // Gets the children of the parent, ie. the siblings of this file
+      console.log(err, siblings);
```
Comment (alanshaw) [inline lib/get-archive-and-children.js]: Please remove

**Comment by alanshaw** [comment]
Please merge this in yourself after you remove that `console.log` :)
