### PR TITLE
Fixes issue with organisations of type 'institution'

### LINKED ISSUE #835: Some people pages are failing
It looks like the way the index stores `organisation` type has changed to `institution` in some case.
http://localhost:8000/people/ap24975/ferranti-limited

```
"summary_title": "Ferranti Limited",
"type": {
"base": "agent",
"type": "institution"
}
```
```
TypeError: Uncaught error: Cannot convert undefined or null to object
    at Function.keys (native)
    at Object.agent (/Users/jamie/projects/collectionsonline/lib/transforms/json-ld.js:28:15)
    at module.exports (/Users/jamie/projects/collectionsonline/lib/transforms/json-to-html-data.js:32:57)
    at /Users/jamie/projects/collectionsonline/routes/person.js:68:24
    at /Users/jamie/projects/collectionsonline/lib/get-related-items.js:35:14

```

### PR DESCRIPTION
**Pull request by jamieu**
Added in an additional check for `institutions` to `isOrganisation`.

Resolves #835

(Just realised I've accidentally merged in the commits from my other branch / PR. This PR is related to #835 - and only affects one file `lib/transforms/get-values.js `https://github.com/TheScienceMuseum/collectionsonline/pull/836/commits/02eec49f11bc30b966aca0b4df9927b19cbb924c - although no harm in both PR's going live at once (although let me know if you'd prefer me to open a new PR for this issue).

### CODE REVIEW

File: lib/facets/create-facets.js [hunk 1]
```diff
@@ -22,6 +22,9 @@ module.exports = function createAllFacets (results) {
       if (v.key === 'Science Museum' || v.key === 'National Railway Museum' || v.key === 'Museum of Science and Industry' || v.key === 'National Media Museum') {
         return {
           value: v.key,
+          // really don't like this 'fix' but can't think of a better (short term) solution?
```
Comment (nelsonic) [inline lib/facets/create-facets.js]: agree, not ideal. but will work. 👍

File: lib/helpers/search-results-to-template-data/title-page.js [hunk 2]
```diff
@@ -19,6 +19,9 @@ var nameFromFilter = function (selectedFilters) {
     return f !== 'categories' && f !== 'museum' && f !== 'gallery';
   });
 
+  // temporary fix for renamed musuem (this really needs updating in the ES index)
```
Comment (nelsonic) [inline lib/helpers/search-results-to-template-data/title-page.js]: is there an issue/task for updating in the ES Index?
