### PR TITLE
Visual fixes

### LINKED ISSUE #152: Text for citation copy/past widget
For the block on the RHS...

Science Museum Group. "Page title.” Inventory number. Science Museum Group Collection Online. Accessed (today’s date). URL.”

* Page title:  object name / person name / document titke
* Inventory number: accession no.
* Today's date: July 06, 2016
* URL: the url of the page

All other text as above including full stops.

### PR DESCRIPTION
**Pull request by Danwhy**
closes #152, #155, #170

### CODE REVIEW

File: templates/helpers/gettodaysdate.js [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+    'May',
+    'June',
+    'July',
+    'August',
+    'September',
+    'October',
+    'November',
+    'December'
+  ];
+  var today = new Date(Date.now());
```
Comment (SimonLab) [inline templates/helpers/gettodaysdate.js]: can we simplify with just
```
var today = new Date();
```
?

**Comment by SimonLab** [comment]
Just one small comment otherwise LGTM

File: client/routes/search.js [hunk 2]
```diff
@@ -45,6 +45,10 @@ module.exports = function (page) {
       var pageEl = document.getElementsByTagName('main')[0];
       pageEl.innerHTML = Templates['search'](ctx.state.data);
 
+      // Shows filter toggle button if javascript enabled
+      document.getElementById('fb').className = 'control__button';
```
Comment (nelsonic) [inline client/routes/search.js]: is the objective to _overwrite_ the class on this element or add an additional one? 
e.g. should it be `document.getElementById('fb').className += 'control__button';`
see: http://stackoverflow.com/questions/13980982/add-class-to-html-with-javascript

Comment (Danwhy) [inline client/routes/search.js]: The button has the class `"control__button hidden"` to begin with. I want to remove the 'hidden' class

File: client/routes/search.js [hunk 3]
```diff
@@ -45,6 +45,10 @@ module.exports = function (page) {
...
+      document.querySelector('button.filterpanel__button').className = 'hidden';
```
Comment (nelsonic) [inline client/routes/search.js]: I understand you want to _overwrite_ here... why not in-line it instead of apply a class?
`document.querySelector('button.filterpanel__button').style.display = 'none';`

File: public/hide.js [hunk 4]
```diff
@@ -3,4 +3,6 @@ if (!document.querySelector('input.filter__box:checked')) {
   document.getElementById('searchresults').className = 'row searchresults';
   document.getElementById('filtercolumn').className = 'filtercolumn';
   document.getElementById('control--filters').className = 'control control--filters';
+  document.getElementById('fb').className = 'control__button';
```
Comment (nelsonic) [inline public/hide.js]: Does this code only get run on a specific route?
(_if not it's dupe of `client/routes/search.js` ..._)

File: templates/helpers/getinventorynumber.js [hunk 5]
```diff
@@ -0,0 +1,4 @@
+module.exports = (details) => {
+  var accession = details.find(el => el.key === 'Accession Number');
```
Comment (nelsonic) [inline templates/helpers/getinventorynumber.js]: is this `.find` being _transpiled_?
(Internet Explorer will choke on it... https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Browser_compatibility )

File: public/hide.js (hunk 4 above)
Comment (Danwhy) [inline public/hide.js]: The code in `client/routes/search` doesn't get run on the initial render. This file is run before anything else to avoid the box flashing before it's hidden

File: templates/helpers/getinventorynumber.js (hunk 5 above)
Comment (Danwhy) [inline templates/helpers/getinventorynumber.js]: No, I should rewrite this

File: templates/helpers/gettodaysdate.js [hunk 6]
```diff
@@ -0,0 +1,19 @@
+module.exports = () => {
```
Comment (nelsonic) [inline templates/helpers/gettodaysdate.js]: want an _easy_ way of writing this?
try:
```js
var options = { day: 'numeric', month: 'long', year: 'numeric' };
return new Date().toLocaleDateString('en-GB', options);
```
see: https://repl.it/Cbfv/2 (_output is identical_) 😉

File: templates/partials/search/results-page.html [hunk 7]
```diff
@@ -15,7 +15,7 @@
     <div class="large-3 medium-4 small-6 columns">
       <div class="control control--filters control--active" id="control--filters">
           <label class="control__label" for="fb">Refine search</label>
-          <button class="control__button" id="fb">{{> global/icon i="filter_list" }}</button>
+          <button class="control__button hidden" id="fb">{{> global/icon i="filter_list" }}</button>
```
Comment (nelsonic) [inline templates/partials/search/results-page.html]: Ok. cool. if you're going to _hide_ it initially and only display if JS is available... 👍

File: client/routes/search.js (hunk 2 above)
Comment (nelsonic) [inline client/routes/search.js]: Cool. ✅

File: public/hide.js (hunk 4 above)
Comment (nelsonic) [inline public/hide.js]: Got it. 👍

File: templates/helpers/getinventorynumber.js (hunk 5 above)
Comment (nelsonic) [inline templates/helpers/getinventorynumber.js]: Ping me when done. 👍

**Comment by nelsonic** [comment]
Gents, code looks good. left a couple of comments. ping me when ready for second review. 👍

**Comment by Danwhy** [comment]
@nelsonic Ready when you are

**Comment by nelsonic** [comment]
Looks good. 
we should attempt to get test coverage back up in the next PR. 
🚢
